document:
  name: Linee Guida su acquisizione e riuso di software per le pubbliche amministrazioni
  description:
      Linee guida in attuazione dagli articoli 68 e 69 del Codice dell’Amministrazione Digitale
  tags:
    - open source
    - linee guida
    - riuso
    - software
